version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - echo $AWS_DEFAULT_REGION
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/w3s5h2n2 
      - REPOSITORY_URI=704751486237.public.ecr.us-east-1.amazonaws.com/w3s5h2n2/demo
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t 704751486237.public.ecr.us-east-1.amazonaws.com/w3s5h2n2/demo:latest .
      - docker tag 704751486237.public.ecr.us-east-1.amazonaws.com/w3s5h2n2/demo:latest 704751486237.public.ecr.us-east-1.amazonaws.com/w3s5h2n2/demo:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - docker push 704751486237.public.ecr.us-east-1.amazonaws.com/w3s5h2n2/demo:latest
      - docker push 704751486237.public.ecr.us-east-1.amazonaws.com/w3s5h2n2/demo:$IMAGE_TAG
